language: python
python:
  - "2.6"
  - "2.7"
# install libhdf5 so pytables can link against it
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libhdf5-serial-dev
# commands to install ulmo
install: 
  - "python -c 'import numpy; print numpy.version.version'"
  - "pip install 'python-dateutil<2'"
  - "pip install numexpr"
  - "pip install cython"
  - "pip install tables"
  - "pip install ."
  - "pip install sure"
  - "pip install freezegun"
  - "pip install pytest"
  - "pip install httpretty"
  - "pip install html5lib"

# command to run tests
script: "py.test"
